name: SemVer Tag from PR
inputs:
  trunk:
    description: trunk of the repository
    required: true
    default: main
  label-major:
    description: label override for major changes
    required: true
    default: merge-major
  label-minor:
    description: label override for minor changes
    required: true
    default: merge-minor
  label-patch:
    description: label override for patch changes
    required: true
    default: merge-patch
  label-none:
    description: label override for none changes
    required: true
    default: merge-none
  repo-token:
    description: gh token with permissions contents.write and pull-requests.read
    required: true
  repo-storage-path-overwrite:
    description: path where the repository is cloned. Defaults to GITHUB_WORKSPACE
    required: false
  should-set-tag:
    description: whether tag should be added to the cloned repo inside gh actions
    required: true
    default: "true"
  should-push-tag:
    description: whether tag should be pushed to the original repo
    required: true
    default: "true"
outputs:
  old-tag:
    description: the old tag before applying the semVer-bump
  new-tag:
    description: the new tag after applying the semVer-bump
runs:
  using: docker
  image: docker://ghcr.io/simontheleg/semver-tag-from-pr-action:v1.0.2
