name: SemVer Tag from PR
inputs:
  trunk:
    description: trunk of the repository
    required: true
    default: main
  label-major:
    description: label override for major changes
    required: true
    default: merge-major
  label-minor:
    description: label override for minor changes
    required: true
    default: merge-minor
  label-patch:
    description: label override for patch changes
    required: true
    default: merge-patch
  label-none:
    description: label override for none changes
    required: true
    default: merge-none
  repo-token:
    description: gh token with permissions contents.write and pull-requests.read
    required: true
  repo-storage-path-overwrite:
    description: path where the repository is cloned. Defaults to GITHUB_WORKSPACE
    required: false
  should-set-tag:
    description: whether tag should be added to the cloned repo inside gh actions
    required: true
    default: "true"
  should-push-tag:
    description: whether tag should be pushed to the original repo
    required: true
    default: "true"
outputs:
  old-tag:
    description: the old tag before applying the semVer-bump
  new-tag:
    description: the new tag after applying the semVer-bump
# unfortunately I could not find a good way to ensure that the GIT_REF of the action
# always matches the image (e.g. using @v1.1.0 would automatically use v1.1.0 image and so on)
# Things tried:
# - use ${{ github.action_ref }} directly inside runs.image -> context 'github' is not available in this section
# - templating the version using the release action -> unfortunately action cannot push to protected branch
# - using a composite action which then pulls the the image -> this allows for using github.action_ref, but you will
#   have to map every single input into an environment variable for it to work
# runs:
#   using: composite
#   steps:
#     - name: run semver-tag-on-merge action
#       shell: bash
#       env:
#         VERSION: ${{ github.action_ref }}
#       run: docker run --env-file <(env) ghcr.io/simontheleg/semver-tag-from-pr-action:${VERSION}
#
# => so for now we have to settle with this not super performant alternative of re-building the image.
# as development on this slows down, it might make sense to hardcode a tag here
runs:
  using: docker
  image: Dockerfile
