name: push-container-branch
on:
  push:
    branches:
      - "**"

jobs:
  push_container:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and push container-image
        run: |
          IMAGE_NAME="ghcr.io/simontheleg/semver-tag-from-pr-action"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker build . -t ${IMAGE_NAME}:branch-${GITHUB_REF_NAME}
          docker push ${IMAGE_NAME}:branch-${GITHUB_REF_NAME}
