on:
  push:
    branches:
      - main

jobs:
  semver_tag_from_pr:
    permissions:
      contents: write
      pull-requests: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: determine tag
        id: determine-tag
        uses: simontheleg/semver-tag-from-pr-action@v1.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          label-major: merge-breaking
          label-minor: merge-feature
          label-patch: merge-fix
          label-none: merge-no-new-version
          should-set-tag: "false"
      - name: update action yaml
        env:
          old_version: ${{ steps.determine-tag.outputs.old-version }}
          new_version: ${{ steps.determine-tag.outputs.new-version }}
        run: |
          sed -i "s/${old_version}/${new_version}/g" action.yml
          cat action.yml
          git add action.yml
          git commit -m "auto: bump docker image to ${new_version}"
      - name: push tag
        env:
          new_version: ${{ steps.determine-tag.outputs.new-version }}
        run: |
          git tag ${new_version} -a ${new_version}
          git push origin ${new_version}
