on:
  push:
    branches:
      - main

jobs:
  semver_tag_from_pr:
    permissions:
      contents: write
      pull-requests: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: determine tag
        id: determine-tag
        uses: simontheleg/semver-tag-from-pr-action@v1.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          label-major: merge-breaking
          label-minor: merge-feature
          label-patch: merge-fix
          label-none: merge-no-new-version
          should-set-tag: "false"
      - name: update action yaml
        run: |
          sed -i 's/${{ steps.determine-tag.outputs.old-version }}/${{ steps.determine-tag.outputs.new-version }}/g' action.yml
          cat action.yml
          git add action.yml
          git commit -m "auto: bump docker image to ${{ steps.determine-tag.outputs.new-version }}"
      - name: push tag
        uses: simontheleg/semver-tag-from-pr-action@v1.0.2
        run:
          git tag ${{ steps.determine-tag.outputs.new-version }} -a ${{ steps.determine-tag.outputs.new-version }}
          git push origin ${{ steps.determine-tag.outputs.new-version }}
